version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080

  dashboard:
    build: ./dashboard
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  sensor-simulator:
    build: ./sensor-simulator
    depends_on:
      - kafka
